#!/bin/bash
#
# sshgit - Constants and Version
#

readonly VERSION="1.2.0"
readonly SCRIPT_NAME="sshgit"
readonly CONFIG_FILE="$HOME/.sshgitrc"
readonly SSH_DIR="$HOME/.ssh"
readonly SSH_CONFIG="$SSH_DIR/config"
readonly SSHGIT_MARKER="# generated by sshgit"
readonly VALID_KEY_TYPES=("ed25519" "rsa" "ecdsa")
